### ISSUE TITLE
Improve Javascript style

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/CarbonFootprintGoogleMaps#10]
The current code does not adhere to typical Javascript style conventions. The code should be improved according to Google's Javascript Style Guide (e.g. https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml) or other well-know style guide.

The code should also be properly commented, also according to style guides.

**Comment by goelrohan6** [comment]
Is the issue still open? as it is already merged.

**Comment by rohankatyal29** [comment]
@goelrohan6: The only major thing to refactor is the length of certain lines

**Comment by Ceilican** [comment]
I will repeat here what I said for Mind The Word:

@goelrohan6 , The merged pull request https://github.com/OiWorld/MindTheWord/pull/60 (by @rohankatyal29) already does the most important improvements. However, [Google's Javascript Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml) gives other recommendations that could still be taken into account. Therefore, I leave this issue still open for now.

Nevertheless, anyone interested in doing working on this issue should coordinate with others already working on this. It's ok to have many people working on the same issue, but you should try not to do exactly the same thing. In this spirit, I propose that whoever wants to continue working on this issue should preferably first declare here on which aspect of the [Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml) you will work on.

Thank you all!

**Comment by dracarys09** [comment]
Hi, I would like to help with this issue.
Can you help me in understanding the workflow ?

**Comment by Ceilican** [comment]
@dracarys09 , this issue has already been solved. I will close it now. But you are welcome to work on any other issue. The workflow is: 

1) tell us that you are going to work on issue X;

2) work on issue X; ask for our help, if necessary.

3) submit a pull request with what you did, when you finish doing it.
