### ISSUE TITLE
Estimate travel cost

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/CarbonFootprintGoogleMaps#11]
It would be easy to generalize this extension to estimate not only the CO2 emissions of a route but also the fuel costs (in money). This is interesting information, since a high cost is another incentive for the user not to use his car. 

The options page should allow the user to specify the price of fuel per litre (or gallon) and choose whether he wants the travel cost to be displayed together with the CO2 emissions.

**Comment by rohankatyal29** [comment]
@Ceilican: We will need the user to input the mileage as well, won't we?

**Comment by Ceilican** [comment]
Yes. This is already partially done in one of the open pull requests.

**Comment by goelrohan6** [comment]
@Ceilican I have added the required features and edited the required files.
please review all my pull requests 
#20 ,  #21 , #22 , #23 , #24
tell me my mistakes so that i can improve
Thankyou .

**Comment by rohankatyal29** [comment]
Can you point me to that PR? I have completed the other part with the fuel cost

**Comment by rohankatyal29** [comment]
@goelrohan6: Just a slight suggestion. All the PRs that you have created are contributing towards the same feature and so are the commits. You can squash all those commits into 1 and just raise 1 PR for this.

**Comment by Ceilican** [comment]
@rohankatyal29 : The pull request is https://github.com/OiWorld/CarbonFootprintGoogleMaps/pull/14 . I'm waiting for @PrateekGupta1509 to do a few improvements, before merging it.

**Comment by rohankatyal29** [comment]
Thanks @Ceilican

**Comment by Ceilican** [comment]
@goelrohan6 : indeed you should submit a single pull request containing all your changes. The general rule is: one pull request per feature or bug fix.

So, I will wait for you to resubmit a single pull request, ok?

**Comment by Ceilican** [comment]
I will be away in the next 48 hours, without internet connection.

**Comment by goelrohan6** [comment]
@Ceilican sorry for such a mistake , i slipped a bit with git , will not commit such a mistake in future.
And i have pulled a req #26 regarding the same.
Thankyou
