### ISSUE TITLE
CO2 Emissions not showing

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/CarbonFootprintGoogleMaps#16]
@rohankatyal29 noticed the following issue:

> I am not being able to run the extension on chrome. It gets installed perfectly fine, but I don't see the carbon emissions next to the total distance. This happens even if I install the extension from chrome store. Any particular why this might be happening? 

Thank you for noticing this!

The extension performs the following major steps:
1) it finds the route's distance in Google Maps webpage
2) it calculates the emissions
3) and, finally, it inserts the emissions back into the webpage.

For steps 1 and 3, the extension needs to navigate the DOM of the webpage. The problem is that, from time to time, Google restructures the DOM, and this breaks the functionality of Carbon Footprint.

It seems that, unfortunately, this has just happened again. It has happened twice before in the last 4 years.

To fix this issue, one needs to look at all lines in the code where we are traversing the page's DOM elements and inserting new DOM elements to the page. These are lines containing "document.getElementsBy...", for instance. It is also necessary to look at the new source code of Google Maps's page, to see which tags, ids and structures they are using now, in order to know how to traverse the new DOM correctly.

This is an excellent puzzle for GSoC. Solving it definitely shows mastery in the necessary skills to work in this project.

**Comment by rohankatyal29** [comment]
Hi @Ceilican, 

This issue has been resolved in PR #17. 
Please review it and let me know if any changes are required.

**Comment by Ceilican** [comment]
I will check it tonight.

**Comment by srikar0896** [comment]
hello ceilican,
can you please send the link of the repository for this bug.?
Thank you

**Comment by ExC0d3** [comment]
![screenshot from 2016-03-06 13 35 39](https://cloud.githubusercontent.com/assets/8655624/13553040/7eee14e0-e3a0-11e5-9c5d-2744275dae03.png)

I pulled the latest code, and it seems to be working for now.

Also I noticed that

**chrome.extension.sendRequest** is being used instead of
**chrome.extension.sendMessage**

which has been deprecated [See this](https://developer.chrome.com/extensions/extension#method-sendRequest)

**Comment by Ceilican** [comment]
@ExC0d3 , thanks for noticing the deprecation! Could you fix the deprecation and submit a pull request?

**Comment by Ceilican** [comment]
Issue resolved in pull request https://github.com/OiWorld/CarbonFootprintGoogleMaps/pull/17.
