### ISSUE TITLE
The Carbon emission values shown on map are not synced with options page 

### ISSUE THREAD

**Issue by ayush1997** [OiWorld/CarbonFootprintGoogleMaps#35]
Hi,
I pulled the latest code and loaded the extension.But the carbon emission values are not changing with changes in the options page.
![s1](https://cloud.githubusercontent.com/assets/15091994/13729150/8da5f796-e954-11e5-99bd-f43c0e2854b5.png)
![s2](https://cloud.githubusercontent.com/assets/15091994/13729153/94a474d2-e954-11e5-8838-28615ce9fe67.png)
![s3](https://cloud.githubusercontent.com/assets/15091994/13729155/9e5e043e-e954-11e5-903f-9d251836045f.png)
![s4](https://cloud.githubusercontent.com/assets/15091994/13729156/a2900f66-e954-11e5-9458-644f1063b7a7.png)

I changed the value from 100 to 200 but map showed the same content.
The reason which I found was 
`var carbonEmission = 217;` -> GoogleMapsCarbonFootprint.js file

the variable was set to constant and not taking the values from option page.

**Comment by ayush1997** [comment]
I have pushed the code in PR#36 which resolves the above problem.

**Comment by Ceilican** [comment]
Thanks!
