### ISSUE TITLE
Port this extension to Safari

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/CarbonFootprintGoogleMaps#7]
The port should be done in a way that both versions (Chrome and Safari) share as much code as possible, in order to facilitate maintenance.

**Comment by rohankatyal29** [comment]
@Ceilican: Do you have a Apple Developer Account that I can use to port this?

**Comment by Ceilican** [comment]
Not yet. But I think this issue should not be addressed yet. It is not simple enough to be a GSoC puzzle. I will create an account before the coding period begins.  If you would like to work on this issue, please promise to do so in your GSoC application, and briefly explain how you are going to do it and what you are going to need.

**Comment by rohankatyal29** [comment]
Okay, makes sense. Will mention the details in my application
