### ISSUE TITLE
Improve the design of the options page

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/CarbonFootprintGoogleMaps#8]
The current options page is too ugly for modern web design standards. It needs to be improved.

**Comment by PrateekGupta1509** [comment]
@Ceilican I would like to work on this. And would also like to know if i can add jquery ?

**Comment by Ceilican** [comment]
Sorry for the delay in replying.

Yes, you can use JQuery.

**Comment by share-with-me** [comment]
Does the UI redesigning (#8 issue) still stay open?
